### ISSUE TITLE
Option to add amount of bitcoins

### ISSUE THREAD

**Issue by sanderkoenders** [MakG10/plasma-applet-bitcoin-price#3]
It would be nice to enter the amount of bitcoins a user has so you can track the actual value of the amount of coins you own.

**Comment by MakG10** [comment]
Hi, I actually made something similar a while ago: https://github.com/MakG10/plasma-applet-bitcoin-wallet-balance with only difference that you don't enter the value yourself, but a wallet address(es).

**Comment by sanderkoenders** [comment]
Well, that's even better to be honest :D
