### ISSUE TITLE
[Feature Request] Add coinbe.net exchange

### ISSUE THREAD

**Issue by JuniorJPDJ** [MakG10/plasma-applet-bitcoin-price#6]
Hi,
Can you add support of CoinBe? It's little polish exchange with support of big amount of coins.
There is public API docs: https://github.com/beatcoinpl/Public-API

**Comment by MakG10** [comment]
Hi. Correct me if I'm wrong, but I can't see any fiat - crypto exchanges, only crypto to crypto. Currently this widget can only convert Bitcoin directly to fiat currencies.

**Comment by JuniorJPDJ** [comment]
They temporary closed fiat markets, because of cryptocurrency law situation in Poland :/

**Comment by MakG10** [comment]
It seems like the site is still crypto to crypto only, so I'm closing this issue for now.
